#!/usr/bin/env bash

# Build pre-pruned CUDA & CuDNN tarballs

set -euo pipefail

MONOBASE_PYTHON='3.13'

cd "$(git rev-parse --show-toplevel)"

mkdir -p build/monobase build/cache

docker run --rm \
    --user "$(id -u):$(id -g)" \
    --volume "$PWD/src/monobase:/opt/r8/monobase:ro" \
    --volume "$PWD/build/monobase:/srv/r8/monobase:rw" \
    --volume "$PWD/build/cache:/var/cache/monobase:rw" \
    monobase:latest \
    /opt/r8/monobase/run.sh \
    monobase.cuda \
    "$@"
