#!/usr/bin/env bash

# Build production images

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
rm -f ./dist/monobase*.*
uv build
exec docker build --tag monobase:latest --platform=linux/amd64 .
