#!/usr/bin/env bash

# Build mini image for local development

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
exec docker build --file mini.Dockerfile --tag monobase:mini --platform=linux/amd64 .
