name: CI

on:
  push:
  pull_request:

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv tool run ruff check
      - run: uv tool run ruff format --check
      - run: uv run --python 3.12 --with mypy mypy src

  test:
    name: Test
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: ./script/build.sh
      - run: ./script/test.sh

  build:
    name: Build + release
    needs:
      - test
    permissions:
      contents: read
      id-token: write
    uses: replicate/actions/.github/workflows/buildx.yml@main
    with:
      image: monobase
