name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Ensure only one workflow instance runs at a time. For branches other than the
# default branch, cancel the pending jobs in the group. For the default branch,
# queue them up. This avoids cancelling jobs that are in the middle of deploying
# to production.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: ./script/check.sh

  test:
    name: Test
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: ./script/build.sh
      - run: ./script/test.sh

  test-mini:
    name: Test Mini
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: ./script/build.sh
      - run: ./script/test-mini.sh

  build:
    name: Build + release
    needs:
      - check
      - test
      - test-mini
    permissions:
      contents: read
      id-token: write
    uses: replicate/actions/.github/workflows/buildx.yml@main
    with:
      image: monobase
